### ISSUE TITLE
Placeholder doesn't work

### ISSUE THREAD

**Issue by ndvbd** [UziTech/jquery.toTextarea.js#6]
The placeholder doesn't work for me.

**Comment by UziTech** [comment]
Can you share the code that isn't working?

**Comment by UziTech** [comment]
seems to work on jsfiddle: http://jsfiddle.net/UziTech/4msdgjox/80/

**Comment by ndvbd** [comment]
@UziTech It doesn't work only when you have non empty div:

`<div id="textareaPlaceholder"> </div>`

Maybe it's worth mentioning it in the comments.

Another question if I may. When I write in your jsFiddle two lines (with Enter), it doesn't add div or br. Is it the right behaviour? How can I specify that I want newlines to be converted to <br> or <div>?

**Comment by UziTech** [comment]
The placeholder is only supposed to show when the div is empty. A textarea placeholder does the same thing.

http://jsfiddle.net/UziTech/4msdgjox/82/

When you add an enter it should add a new line `\n` so you can grab the text the same way you can with a textarea

```html
<div id="textareaPlaceholder">line1
line2</div>
```

```js
$("#textareaPlaceholder").text() // "line1\nline2"
```
